version: '3.2'

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local

services:
# PHP Service
  app:
    image: imclement/php:7.4-fpm
    # build:
    #  context: .
    #  dockerfile: docker/Dockerfile
    restart: unless-stopped
    tty: true
    user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

# Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

# Node Service
  node:
    image: tarampampam/node:13-alpine
    volumes:
      - ./:/app:rw
    working_dir: /app
    command: [ ]
    networks:
      - app-network

# Database Service
  db:
    image: mysql:5.7.28
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_NAME: mysql
    volumes:
      - 'dbdata:/var/lib/mysql/'
      - './docker/mysql/my.cnf:/etc/mysql/my.cnf'
    networks:
      - app-network
